apiVersion: apps/v1
kind: Deployment
metadata:
  name: loja-spring-boot-deployment
  labels:
    app: loja-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loja-spring-boot
  template:
    metadata:
      labels:
        app: loja-spring-boot
    spec:
      containers:
      - name: loja-spring-boot
        image: loja-spring-boot
        ports:
        - containerPort: 8080

