apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: loja-spring-boot

images:
- name: api-loja-spring-boot
  newName: alx52/api-loja-spring-boot
  newTag: 1.0.0
- name: loja-spring-boot
  newName: alx52/api-loja-spring-boot
  newTag: 1.0.0
