name: CD
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: build image and push to docker hub
        uses: docker/build-push-action@v1.0.0
        with:
          username: alx52
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: alx52/api-loja-spring-boot
          tags: ${{cat target/version}}, latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: update k8s
        run: |
          kustomize edit set image portfolio=alx52/api-loja-spring-boot:${{ steps.package-version.outputs.current-version }}

      - name: commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Deploy Action"
          git commit -am "change image tag"

      - name: push
        uses: ad-m/github-push-action@master

        

